export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMMUNITY_ADMIN: 'COMMUNITY_ADMIN',
  RESIDENT: 'RESIDENT',
  OWNER: 'OWNER',
  TENANT: 'TENANT',
  SECURITY: 'SECURITY',
  MAINTENANCE: 'MAINTENANCE',
  ACCOUNTANT: 'ACCOUNTANT',
  VISITOR: 'VISITOR',
};
