export const ROUTES = {
  LANDING: '/',
  ABOUT: '/about',
  PRICING: '/pricing',
  CONTACT: '/contact',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  OTP: '/otp',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  COMPLAINTS: '/complaints',
  VISITORS: '/visitors',
  FACILITIES: '/facilities',
  BILLING: '/billing',
  COMMUNITY: '/community',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
  ADMIN: '/admin',
  SUPER_ADMIN: '/super-admin',
  NOT_FOUND: '/404',
};
